// Code generated by "stringer -type LogicState"; DO NOT EDIT

package sysgo

import "fmt"

const _LogicState_name = "LoHiHiZUndefined"

var _LogicState_index = [...]uint8{0, 2, 4, 7, 16}

func (i LogicState) String() string {
	if i >= LogicState(len(_LogicState_index)-1) {
		return fmt.Sprintf("LogicState(%d)", i)
	}
	return _LogicState_name[_LogicState_index[i]:_LogicState_index[i+1]]
}
