// Code generated by "stringer -type LogicValue"; DO NOT EDIT

package sysgo

import "fmt"

const _LogicValue_name = "LoHiHiZUndefined"

var _LogicValue_index = [...]uint8{0, 2, 4, 7, 16}

func (i LogicValue) String() string {
	if i >= LogicValue(len(_LogicValue_index)-1) {
		return fmt.Sprintf("LogicValue(%d)", i)
	}
	return _LogicValue_name[_LogicValue_index[i]:_LogicValue_index[i+1]]
}
