// Code generated by "stringer -type simChanType"; DO NOT EDIT

package sysgo

import "fmt"

const (
	_simChanType_name_0 = "moduleinitializer"
	_simChanType_name_1 = "sensitivity"
)

var (
	_simChanType_index_0 = [...]uint8{0, 6, 17}
	_simChanType_index_1 = [...]uint8{0, 11}
)

func (i simChanType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _simChanType_name_0[_simChanType_index_0[i]:_simChanType_index_0[i+1]]
	case i == 4:
		return _simChanType_name_1
	default:
		return fmt.Sprintf("simChanType(%d)", i)
	}
}
