// Code generated by "stringer -type Value"; DO NOT EDIT

package sysgo

import "fmt"

const _Value_name = "LoHiHiZUndefined"

var _Value_index = [...]uint8{0, 2, 4, 7, 16}

func (i Value) String() string {
	if i >= Value(len(_Value_index)-1) {
		return fmt.Sprintf("Value(%d)", i)
	}
	return _Value_name[_Value_index[i]:_Value_index[i+1]]
}
